### ISSUE TITLE
Pick a framework

### ISSUE THREAD

**Issue by danambrogio** [JackAnansi/kollab#3]
Look into:

- Express.js
- Koa
- Restify
- Hapi

Requirements:

- In demand
- Solid

**Comment by danambrogio** [comment]
You good with Express?

**Comment by pawbs** [comment]
im good with express, install it

express also needs an authentication module (eg: passport), and a security module (maybe in the future after we get something working first)

**Comment by danambrogio** [comment]
Added Express
