### ISSUE TITLE
CRUD error handling

### ISSUE THREAD

**Issue by pawbs** [JackAnansi/kollab#9]
CRUD operations succeed no matter what

-scenarios:
delete/update: ID doesnt exist
create, update: field doesnt exist
create/update: unique username collision (users table schema should also be modified)

**Comment by danambrogio** [comment]
Is that just because we always return a 200 response code?

**Comment by pawbs** [comment]
@JackAnansi correct

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
